service: test-tic-tac-toe
app: test-tic-tac-toe
org: mauromoreno

provider:
  name: aws
  runtime: nodejs10.x
  stage: local
  region: ${file(./env.yml):${opt:stage, self:provider.stage}.AWS_REGION_CODE}
  environment: ${file(./env.yml):${opt:stage, self:provider.stage}}

package:
  exclude:
    - .git

functions:
  games-list:
    handler: src/functions/games/list.handler
    events:
      - http:
          path: /games
          method: get
          integration: lambda

plugins:
  - serverless-dynamodb-local
  - serverless-offline

custom:
  dynamodb:
    stages:
      - local
    start:
      migrate: true
